In [8]:
# Load csv data into pandas dataframe
## import libraries
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

## settings for plotting
sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (10,6)

## read in data from csv
df = pd.read_csv('starbucks.csv')

## preview data
df.head()

,Beverage_category,Beverage,Beverage_prep,Calories,Total Fat (g),Trans Fat (g),Saturated Fat (g),Sodium (mg),Total Carbohydrates (g),Cholesterol (mg),Dietary Fibre (g),Sugars (g),Protein (g),Vitamin A (% DV),Vitamin C (% DV),Calcium (% DV),Iron (% DV),Caffeine (mg)
0,Coffee,Brewed Coffee,Short,3,0.1,0.0,0.0,0,5,0,0,0,0.3,0%,0%,0%,0%,175
1,Coffee,Brewed Coffee,Tall,4,0.1,0.0,0.0,0,10,0,0,0,0.5,0%,0%,0%,0%,260
2,Coffee,Brewed Coffee,Grande,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,0%,0%,330
3,Coffee,Brewed Coffee,Venti,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,2%,0%,410
4,Classic Espresso Drinks,Caffè Latte,Short Nonfat Milk,70,0.1,0.1,0.0,5,75,10,0,9,6.0,10%,0%,20%,0%,75

In [15]:
# information about data 

## describe data
df.info()

## find missing values
print("\nNull values:")
df.isnull().sum()

## summary statistics
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Beverage_category          242 non-null    object
 1   Beverage                   242 non-null    object
 2   Beverage_prep              242 non-null    object
 3   Calories                   242 non-null    int64
 4    Total Fat (g)             242 non-null    object
 5   Trans Fat (g)              242 non-null    float64
 6   Saturated Fat (g)          242 non-null    float64
 7    Sodium (mg)               242 non-null    int64
 8    Total Carbohydrates (g)   242 non-null    int64
 9   Cholesterol (mg)           242 non-null    int64
 10   Dietary Fibre (g)         242 non-null    int64
 11   Sugars (g)                242 non-null    int64
 12   Protein (g)               242 non-null    float64
 13  Vitamin A (% DV)           242 non-null    object
 14  Vitamin C (% DV)           242 non-null    object
 15   Calcium (% DV)            242 non-null    object
 16  Iron (% DV)                242 non-null    object
 17  Caffeine (mg)              241 non-null    object
dtypes: float64(3), int64(6), object(9)
memory usage: 34.2+ KB

Null values:

,Calories,Trans Fat (g),Saturated Fat (g),Sodium (mg),Total Carbohydrates (g),Cholesterol (mg),Dietary Fibre (g),Sugars (g),Protein (g)
count,242.000000,242.000000,242.000000,242.000000,242.000000,242.000000,242.000000,242.000000,242.000000
mean,193.871901,1.307025,0.037603,6.363636,128.884298,35.991736,0.805785,32.962810,6.978512
std,102.863303,1.640259,0.071377,8.630257,82.303223,20.795186,1.445944,19.730199,4.871659
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,120.000000,0.100000,0.000000,0.000000,70.000000,21.000000,0.000000,18.000000,3.000000
50%,185.000000,0.500000,0.000000,5.000000,125.000000,34.000000,0.000000,32.000000,6.000000
75%,260.000000,2.000000,0.100000,10.000000,170.000000,50.750000,1.000000,43.750000,10.000000
max,510.000000,9.000000,0.300000,40.000000,340.000000,90.000000,8.000000,84.000000,20.000000